name: marketmove_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.12.0
  supabase: ^2.10.2
  functions_client: ^2.5.0
  gotrue: ^2.18.0
  postgrest: ^2.6.0
  realtime_client: ^2.7.0
  sign_in_with_apple: ^7.0.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
